# 使用官方Python镜像作为基础
FROM python:3.8

# 设置工作目录
WORKDIR /spider

# 将当前目录下的所有文件复制到容器内的 /spider 目录中
COPY . /spider/

# 安装项目依赖
RUN pip install -r requirements.txt

# 启动 Scrapy 项目（根据你的项目名称和运行命令进行修改）
# CMD ["scrapy", "crawl", "your_spider_name"]
