version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # 这里指定你的 Dockerfile 文件
    ports:
      - "8000:8000"  # 将容器内的 8000 端口映射到主机的 8000 端口
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=WebBacked.settings
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dbase
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
