version: '3'

services:
  web:
    image: python:3.8
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=WebBacked.settings
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dbase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
